Add MPR installation instructions
taiki-e/parse-changelog pull request #23
Opened 2022-06-11 20:18 UTC by hwittenborn

2022-06-11 20:22 UTC, hwittenborn commented
Should instructions for installing makedeb also be included? Users might be confused if they don't have it on there system and there wondering why something isn't working.

Should Prebuilt-MPR instructions also be added? It would avoid the need for makedeb to be installed in the first place, and would only require adding an APT repository, which a lot of projects already do

2022-06-17 10:18 UTC, taiki-e requested changes
Thanks!

> Should instructions for installing makedeb also be included? Users might be confused if they don't have it on there system and there wondering why something isn't working.

I tend not to include makedeb's installation instructions. Our installation instructions are for users of package managers, and new users of package managers can learn more about it through links to the package.

Also, the package manager's recommended installation instructions may change. (In fact, rustup's recommended installation instructions have been updated in the past for better security. Some projects explain rustup's the old installation instructions in their readme, but that is not a nice situation for new users.)

> Should Prebuilt-MPR instructions also be added? It would avoid the need for makedeb to be installed in the first place, and would only require adding an APT repository, which a lot of projects already do.

Sounds good to have it.

2022-06-17 19:53 UTC, hwittenborn commented on README.md
> +You can install [parse-changelog from the MPR](https://mpr.makedeb.org/parse-changelog):
Sorry about that :P I'll get it fixed right now

2022-06-18 07:09 UTC, taiki-e approved these changes
bors r+

2022-06-18 07:14 UTC, merged